modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
[[mods]]
modId="iron_fence"
version="1.0.0"
displayName="Iron Fence"
logoFile=""
credits=""
displayURL="https://github.com/XGJSJS/Iron-Fence"
authors="XGJS"
description='''
Add iron fence
'''
[[dependencies.iron_fence]]
    modId="iron_fence"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iron_fence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
