license="${mod_license}"
issueTrackerURL="https://github.com/XGJSJS/Iron-Fence" #optional
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://space.bilibili.com/1328815668"
logoFile="icon.png"
authors="XGJS"
description='''
Add 6 different kinds of fences.
'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"